apiVersion: v1
kind: Pod
metadata:
  name: application
  namespace: webapp
spec:
  containers:
    - name: websrv-images
      image: 
      env:
        - name: DBPWD
          value: pw
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql.database.svc.cluster.local"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080
