apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: webapp
spec:
  containers:
    - name: websrv-images
      image: 699068936389.dkr.ecr.us-east-1.amazonaws.com/websrv-images:v0.1
      env:
        - name: DBPWD
          value: pw
        - name: DBUSER
          value: root
        - name: DBHOST
          value: pod ip
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080