apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rep
  namespace: sqldb
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-images
          image: 699068936389.dkr.ecr.us-east-1.amazonaws.com/mysql-images:v0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pw
          ports:
            - containerPort: 3306
